version: "3.8"

services:
  node_app:
    container_name: node_app
    build: .
    image: MarcoTuTerror2/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=marco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=marco
      - POSTGRES_PASSWORD=12345
    volumes: 
      - node_db_data:/var/lib/postgresql/data
#dOCKER VOLUMES PARA TRABAJAR CON PERSISTENCIA EN LOS CONTENEDORES
volumes:
  node_db_data: {}